### ISSUE TITLE
根根就启动不起来

### ISSUE THREAD

**Issue by LDM456** [Yuezi32/react-family#4]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (D:\Cloud\React\react-family-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\Cloud\React\react-family-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:317:13)
    at D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\Cloud\React\react-family-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\Cloud\React\react-family-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:317:13)
    at D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Cloud\React\react-family-master\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\Cloud\React\react-family-master\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\Cloud\React\react-family-master\node_modules\express\lib\router\layer.js:95:5)

**Comment by haoygit** [comment]
https://blog.csdn.net/weixin_43453221/article/details/109525223 试下这个第二种方法，我的好了
